[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "shawdoc"
authors = [{name = "Shaw", email = "et_shaw@126.com"}]
dynamic = ["version", "description"]
